apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: web  # Assumes 'web' namespace exists (or remove for default)
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 3  # Maintains 3 identical pods
  selector:    # Matches pods to manage
    matchLabels:
      app: nginx
      tier: frontend
  template:    # Pod template for new replicas
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine  # Lightweight version
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5