apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev  # Applies only in the "default" namespace
  name: pod-reader
rules:
- apiGroups: [""]  # Core API group (pods, services, etc.)
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
