apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default  # Must match the Role's namespace
subjects:
- kind: User
  name: alice  # User in Kubernetes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader  # Must match the Role's name
  apiGroup: rbac.authorization.k8s.io
